import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import UserContextProvider from "./context/UserContextProvider";
import Image from "next/image";
import Link from "next/link";
import NavigationList from "./components/helperComponent/navigationList";
import Footer from "./components/footer";
import GlobalContextProvider from "./context/globalContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="winter">
      <body className={inter.className}>
        <div className="flex flex-col">
          <GlobalContextProvider>
            <UserContextProvider>{children}</UserContextProvider>
          </GlobalContextProvider>
          <Footer />
        </div>
      </body>
    </html>
  );
}
